import type { CurriculumLevel, CurriculumLesson, CurriculumModule, LessonStatus } from "./types";

function lesson(
  slug: string,
  title: string,
  summaryOrStatus: string,
  status: LessonStatus = "published",
  minutes = 7,
): CurriculumLesson {
  if (summaryOrStatus === "published" || summaryOrStatus === "locked") {
    return {
      slug,
      title,
      minutes,
      status: summaryOrStatus,
      summary: `${title} is on this level’s syllabus and unlocks with the level.`,
    };
  }
  return { slug, title, minutes, summary: summaryOrStatus, status };
}

function mod(id: string, title: string, lessons: CurriculumLesson[]): CurriculumModule {
  return { id, title, lessons };
}

const open = "published" as const;
const later = "locked" as const;

export const COURSE_RULES = [
  "Never promised or implied guaranteed profits.",
  "Educational patterns are not buy or sell signals.",
  "Every strategy must include a stop-loss and a position-sizing rule.",
  "Futures and options stay locked until you pass risk training.",
  "Paper trading comes before any live broker integration.",
  "Backtests must include brokerage, taxes and slippage, and are past performance only.",
] as const;

export const LEVELS: CurriculumLevel[] = [
  {
    id: 1,
    name: "Stock Market Foundations",
    goal: "Understand how Indian markets work, who participates, how orders fill, and what it costs to trade.",
    modules: [
      mod("markets", "How the market works", [
        lesson("what-is-the-stock-market", "What is the stock market?", "A marketplace where ownership in companies is bought and sold between investors, not a machine that prints guaranteed returns."),
        lesson("how-the-stock-market-works", "How the stock market works", "Prices move when buyers and sellers meet. More demand than supply lifts price; the reverse lowers it."),
        lesson("nse-and-bse", "NSE and BSE", "India’s two main exchanges. Most active equity volume is on the NSE; BSE is the older exchange and still lists thousands of companies."),
        lesson("nifty-50-and-sensex", "Nifty 50 and Sensex", "Benchmark indices. Nifty 50 tracks 50 large NSE names; Sensex tracks 30 BSE names. They describe the market, they are not a stock you ‘own’ directly."),
        lesson("primary-and-secondary-market", "Primary and secondary market", "Primary is where companies raise money (IPO). Secondary is where investors trade those shares with each other afterwards."),
        lesson("stocks-and-shares", "Stocks and shares", "A share is a unit of ownership. Stock usually means shares of a company traded on an exchange."),
        lesson("what-are-indices", "What are indices?", "A rules-based basket that measures a group of stocks. You cannot buy an index itself; you buy products that track it."),
        lesson("what-are-etfs", "What are ETFs?", "Exchange-traded funds hold a basket (often an index) and trade like a stock during market hours."),
        lesson("what-are-bonds", "What are bonds?", "A loan to a government or company. You are a creditor, not an owner. Return is mostly interest plus repayment of principal, with credit and rate risk."),
        lesson("what-are-mutual-funds", "What are mutual funds?", "Pooled vehicles managed to a mandate. Units are usually bought/sold at end-of-day NAV, not tick-by-tick like stocks."),
        lesson("what-are-ipos", "What are IPOs?", "A company lists by selling new (or offer-for-sale) shares to the public. Listing price and trading price can differ. IPO allotment is not a guaranteed profit."),
      ]),
      mod("accounts", "Accounts and participants", [
        lesson("demat-account", "Demat account", "Holds securities in electronic form with a depository (NSDL/CDSL) through a depository participant."),
        lesson("trading-account", "Trading account", "The broker account you use to place orders on the exchange."),
        lesson("bank-account-integration", "Bank account integration", "Funds move between your bank and the broker under exchange and SEBI rules. Stocktute never moves real money."),
        lesson("market-participants", "Market participants", "Retail, institutions, FIIs/FPIs, props, and market makers all transact. They have different constraints and time horizons."),
        lesson("retail-investors", "Retail investors", "Individuals trading their own capital. Often shorter research time and higher emotion risk — which this course trains against."),
        lesson("institutional-investors", "Institutional investors", "Mutual funds, insurers, pensions, and similar. Large size means they affect liquidity and often think in quarters, not minutes."),
        lesson("foreign-institutional-investors", "Foreign institutional investors", "Overseas funds investing in India under FPI rules. Flows can move indices, especially in risk-on/risk-off weeks."),
        lesson("market-makers", "Market makers", "Firms that quote two-way prices to supply liquidity. They earn spread, not a promise that your trade is ‘fair’."),
        lesson("brokers-and-dps", "Brokers and depository participants", "The broker routes orders. The DP maintains demat. They can be the same group or separate."),
      ]),
      mod("sessions-orders", "Sessions and order types", [
        lesson("market-timings", "Market timings", "Regular NSE/BSE equity hours are 9:15–15:30 IST, with a pre-open. Always confirm current exchange circulars."),
        lesson("pre-open-and-post-market", "Pre-open and post-market sessions", "Pre-open discovers an opening price. Post-market (if available for that segment) is thinner and easier to slip."),
        lesson("market-order", "Market order", "Fill now at whatever prices are in the book. Fast, but you do not control price. Dangerous in illiquid names."),
        lesson("limit-order", "Limit order", "You set the worst price you will accept. May not fill."),
        lesson("stop-loss-order", "Stop-loss order", "Becomes a market (or limit, if stop-limit) only after a trigger. It reduces, not eliminates, loss — gaps can jump the stop."),
        lesson("stop-limit-order", "Stop-limit order", "Trigger, then a limit. You control price after trigger, but you may not get filled in a fast move."),
        lesson("cover-order", "Cover order", "Intraday structure that pairs entry with a compulsory stop. Still not a profit guarantee."),
        lesson("bracket-order", "Bracket order", "Entry plus stop plus target as a package. Useful for discipline; still subject to fills and gaps."),
        lesson("gtt-order", "Good Till Triggered order", "Broker-side trigger that rests until price hits a condition, even across sessions (subject to broker rules)."),
        lesson("delivery-order", "Delivery order", "You intend to take/give delivery in the cash market. Settlement follows the exchange cycle."),
        lesson("intraday-order", "Intraday order", "Squared off the same day. Overnight gap risk is avoided, but same-day noise and charges still apply."),
      ]),
      mod("microstructure", "Price, liquidity and costs", [
        lesson("bid-price", "Bid price", "The highest price a buyer is currently willing to pay."),
        lesson("ask-price", "Ask price", "The lowest price a seller is currently willing to accept."),
        lesson("bid-ask-spread", "Bid-ask spread", "Ask minus bid. Wide spreads mean higher trading cost, especially for market orders."),
        lesson("trading-volume", "Trading volume", "How many shares traded. Volume confirms participation; it is not a directional crystal ball."),
        lesson("liquidity", "Liquidity", "How easily you can enter/exit near the displayed price. Illiquid stocks punish stops and size."),
        lesson("volatility", "Volatility", "How much price swings. High volatility needs wider stops and smaller size."),
        lesson("market-capitalization", "Market capitalization", "Share price × shares outstanding. A size label, not a quality label."),
        lesson("free-float-market-cap", "Free-float market capitalization", "Value of shares actually available to public trading. Indices often use free-float weights."),
        lesson("upper-circuit", "Upper circuit", "Exchange-set freeze on further up-moves for the session. You may not be able to buy."),
        lesson("lower-circuit", "Lower circuit", "Freeze on further down-moves. You may not be able to sell — a real risk, not a theory."),
        lesson("trading-halt", "Trading halt", "Exchange pauses matching, often around news or stress. Orders may queue or cancel per rules."),
        lesson("settlement-cycle", "Settlement cycle", "When cash and shares actually change hands (e.g. T+1). Trading and settlement are not the same moment."),
        lesson("brokerage", "Brokerage", "What the broker charges. Small on paper, large if you overtrade."),
        lesson("taxes-and-charges", "Taxes and charges", "STT, exchange fees, GST, stamp duty and tax treatment differ by product and holding period. This app does not give tax advice."),
        lesson("slippage", "Slippage", "The difference between the price you hoped for and the price you got. Worst in gaps, news, and thin books."),
      ]),
      mod("corporate-actions", "Corporate actions", [
        lesson("dividends", "Dividends", "Cash (or kind) returned to shareholders. Price often adjusts around the ex-date. Dividends are not ‘free money’."),
        lesson("bonus-shares", "Bonus shares", "Extra shares issued from reserves. Your proportional ownership is unchanged; price adjusts."),
        lesson("stock-splits", "Stock splits", "Face value split, more shares, lower price per share. Economic ownership is unchanged."),
        lesson("rights-issues", "Rights issues", "Existing holders may buy new shares at a set price. Not participating can dilute you."),
        lesson("buybacks", "Buybacks", "Company offers to repurchase shares. Participation rules and tax treatment matter."),
        lesson("mergers", "Mergers", "Companies combine. Share swap ratios change what you own."),
        lesson("demergers", "Demergers", "A business is separated into another listed entity. You typically receive shares in the new company."),
      ]),
    ],
  },
  {
    id: 2,
    name: "Charts and Candlesticks",
    goal: "Read OHLC, timeframes, and candlestick anatomy — then study each pattern as psychology, not a signal.",
    toolHref: { label: "Open AI Classroom", href: "/classroom" },
    modules: [
      mod("chart-types", "Chart types", [
        lesson("line-chart", "Line chart", "Usually plots close. Clean for trend, hides intra-bar rejection."),
        lesson("bar-chart", "Bar chart", "OHLC as a bar. Same data as a candle, different drawing."),
        lesson("candlestick-chart", "Candlestick chart", "Body shows open-to-close; wicks show rejection. The classroom default."),
        lesson("heikin-ashi", "Heikin-Ashi chart", "Averaged candles that smooth noise. They lag and can hide gap risk — do not treat them as raw OHLC."),
        lesson("renko-chart", "Renko chart", "Bricks of a fixed size. Time is not constant. Good for noise reduction, bad for session timing."),
        lesson("point-and-figure", "Point and Figure chart", "Xs and Os of price swing, ignoring time. A specialist view, not a default."),
      ]),
      mod("chart-concepts", "Chart concepts", [
        lesson("open-price", "Open price", "First traded price of the bar. For a day candle, often the 9:15 auction area."),
        lesson("high-price", "High price", "Highest trade in the bar — where buyers ran out of aggression."),
        lesson("low-price", "Low price", "Lowest trade in the bar — where sellers ran out of aggression."),
        lesson("close-price", "Close price", "Last traded price of the bar. Most watched print; still just one print."),
        lesson("volume-on-charts", "Volume", "Participation sitting under price. Rising price on dead volume is a weaker story."),
        lesson("timeframes", "Timeframes", "The same stock can be up on the weekly and down on the 5-minute. Always name the timeframe you are talking about."),
        lesson("price-scale", "Price scale", "How the axis is drawn. Linear vs log changes how trends look on large moves."),
        lesson("logarithmic-scale", "Logarithmic scale", "Equal percent moves take equal space. Useful for long histories."),
        lesson("linear-scale", "Linear scale", "Equal rupee moves take equal space. Fine for short ranges, distorting for multi-year 10x moves."),
        lesson("trends", "Trends", "A series of higher highs and higher lows (up) or the inverse (down). Trends end. They are descriptions, not destinies."),
        lesson("consolidation", "Consolidation", "Price coils in a range after a move. Energy for the next move — direction unknown until it leaves the range."),
        lesson("range", "Range", "A band between support and resistance where mean-reversion is more common than trend-following."),
        lesson("support", "Support", "A zone where buying previously appeared. It can break. Treat it as a hypothesis."),
        lesson("resistance", "Resistance", "A zone where selling previously appeared. Same caveat as support."),
        lesson("trendlines", "Trendlines", "A line across swing points. Subjective. Two analysts will draw different lines — test them."),
        lesson("price-channels", "Price channels", "Parallel trendlines. Useful until they are not; false breaks are common."),
        lesson("gaps", "Gaps", "A jump where no trading occurred. Gaps can fill, partially fill, or never fill."),
        lesson("breakouts", "Breakouts", "Price leaves a range with intent. Needs follow-through; many fail."),
        lesson("false-breakouts", "False breakouts", "A probe beyond the range that snaps back. Stops get run. This is why size and invalidation matter."),
        lesson("pullbacks", "Pullbacks", "A pause against the trend that often retests the breakout zone."),
        lesson("retests", "Retests", "Broken resistance becoming support (or the reverse). Not automatic."),
        lesson("volume-price-relationship", "Volume and price relationships", "Effort vs result. Wide range + high volume is different from wide range + no volume."),
      ]),
      mod("candle-anatomy", "Candle anatomy", [
        lesson("candle-open", "Candle open", "Where the battle started for that bar."),
        lesson("candle-high", "Candle high", "Maximum price printed."),
        lesson("candle-low", "Candle low", "Minimum price printed."),
        lesson("candle-close", "Candle close", "Where the bar settled. Close vs open decides bullish/bearish body."),
        lesson("real-body", "Real body", "The rectangle between open and close. Size shows conviction of that bar only."),
        lesson("upper-wick", "Upper wick", "Rejection of higher prices in that bar."),
        lesson("lower-wick", "Lower wick", "Rejection of lower prices in that bar."),
        lesson("bullish-candle", "Bullish candle", "Close above open. One bar of buying pressure — not a buy signal."),
        lesson("bearish-candle", "Bearish candle", "Close below open. One bar of selling pressure — not a sell signal."),
        lesson("neutral-candle", "Neutral candle", "Open and close nearly equal. Indecision until the next bar votes."),
      ]),
      mod("single-candles", "Single-candle patterns", [
        lesson("doji", "Doji", "Open ≈ close. Pause. Meaning depends entirely on the prior trend and the next close."),
        lesson("long-legged-doji", "Long-Legged Doji", "Large range, tiny body. A violent two-way auction that settled nowhere."),
        lesson("dragonfly-doji", "Dragonfly Doji", "Long lower wick, open/close at the high. Buyers recovered the low — wait for confirmation."),
        lesson("gravestone-doji", "Gravestone Doji", "Long upper wick, open/close at the low. Sellers recovered the high — wait for confirmation."),
        lesson("hammer", "Hammer", "Small body, long lower wick after a decline. A rejection of lower prices, not a guaranteed reversal."),
        lesson("hanging-man", "Hanging Man", "Looks like a hammer but appears after a rally. Potentially bearish only with a weak follow-through."),
        lesson("inverted-hammer", "Inverted Hammer", "Small body, long upper wick after a decline. Needs a higher close next."),
        lesson("shooting-star", "Shooting Star", "Small body, long upper wick after a rally. Rejection of highs; confirm with a lower close."),
        lesson("bullish-marubozu", "Bullish Marubozu", "Little-to-no wick, close at the high. Strong buying in that bar. Still one bar."),
        lesson("bearish-marubozu", "Bearish Marubozu", "Little-to-no wick, close at the low. Strong selling in that bar. Still one bar."),
        lesson("spinning-top", "Spinning Top", "Small body, wicks both sides. Balance / indecision."),
      ]),
      mod("two-candles", "Two-candle patterns", [
        lesson("bullish-engulfing", "Bullish Engulfing", "Green body covers the prior red body after a decline. A shift in bar-to-bar control."),
        lesson("bearish-engulfing", "Bearish Engulfing", "Red body covers the prior green body after a rally."),
        lesson("bullish-harami", "Bullish Harami", "Small body inside a prior large red body. A pause that may become a reversal."),
        lesson("bearish-harami", "Bearish Harami", "Small body inside a prior large green body."),
        lesson("piercing-line", "Piercing Line", "Opens below a red bar’s low/close area and closes above its midpoint."),
        lesson("dark-cloud-cover", "Dark Cloud Cover", "Opens above a green bar and closes below its midpoint."),
        lesson("tweezer-top", "Tweezer Top", "Two bars sharing a similar high after a rally. A ceiling, not a short-sale order."),
        lesson("tweezer-bottom", "Tweezer Bottom", "Two bars sharing a similar low after a decline."),
      ]),
      mod("three-candles", "Three-candle patterns", [
        lesson("morning-star", "Morning Star", "Red bar, small indecision bar, strong green close. Classic three-bar reversal attempt."),
        lesson("evening-star", "Evening Star", "Green bar, small indecision bar, strong red close."),
        lesson("morning-doji-star", "Morning Doji Star", "Morning star whose middle bar is a doji. More indecision in the middle."),
        lesson("evening-doji-star", "Evening Doji Star", "Evening star whose middle bar is a doji."),
        lesson("three-white-soldiers", "Three White Soldiers", "Three rising green closes. Continuation — and a common late-trend trap if stretched."),
        lesson("three-black-crows", "Three Black Crows", "Three falling red closes."),
        lesson("three-inside-up", "Three Inside Up", "Bullish harami plus a confirming higher close."),
        lesson("three-inside-down", "Three Inside Down", "Bearish harami plus a confirming lower close."),
        lesson("three-outside-up", "Three Outside Up", "Bullish engulfing plus a confirming higher close."),
        lesson("three-outside-down", "Three Outside Down", "Bearish engulfing plus a confirming lower close."),
      ]),
    ],
  },
  {
    id: 3,
    name: "Chart Patterns and Indicators",
    goal: "Study structure (H&S, flags, triangles) and indicators as tools with failure modes — never as stacked confirmation theatre.",
    toolHref: { label: "Practice on live charts", href: "/classroom" },
    modules: [
      mod("reversal-patterns", "Reversal patterns", [
        lesson("head-and-shoulders", "Head and Shoulders", "Three peaks, middle highest, neckline break. Measure the height; expect failed patterns."),
        lesson("inverse-head-and-shoulders", "Inverse Head and Shoulders", "Three troughs, middle lowest. Same rules, flipped."),
        lesson("double-top", "Double Top", "Two similar highs and a breakdown. M-shape. Needs a break of the trough."),
        lesson("double-bottom", "Double Bottom", "Two similar lows and a breakout. W-shape."),
        lesson("triple-top", "Triple Top", "Three failed highs. Rarer, often just a range until it is not."),
        lesson("triple-bottom", "Triple Bottom", "Three failed lows."),
        lesson("rounding-top", "Rounding Top", "Slow distribution arc. Hard to time; invalid if price reclaims the midpoint with volume."),
        lesson("rounding-bottom", "Rounding Bottom", "Slow accumulation arc. Same timing problem."),
      ]),
      mod("continuation-patterns", "Continuation patterns", [
        lesson("bull-flag", "Bull Flag", "Sharp up-move, brief downward/sideways flag, then continuation attempt."),
        lesson("bear-flag", "Bear Flag", "Sharp down-move, brief bounce, then continuation attempt."),
        lesson("bull-pennant", "Bull Pennant", "Flag with converging lines after a pole."),
        lesson("bear-pennant", "Bear Pennant", "Pennant after a drop."),
        lesson("rectangle-pattern", "Rectangle Pattern", "Horizontal range. Trade the range or the break — not both without a plan."),
        lesson("cup-and-handle", "Cup and Handle", "Rounded base plus a smaller dip (handle) before a breakout attempt."),
        lesson("inverse-cup-and-handle", "Inverse Cup and Handle", "Distribution version of the cup."),
      ]),
      mod("triangles", "Triangle patterns", [
        lesson("symmetrical-triangle", "Symmetrical Triangle", "Lower highs and higher lows. Direction is unknown until the break."),
        lesson("ascending-triangle", "Ascending Triangle", "Flat top, rising lows. Often bullish, often fails."),
        lesson("descending-triangle", "Descending Triangle", "Flat bottom, falling highs. Often bearish, often fails."),
      ]),
      mod("advanced-patterns", "Advanced patterns", [
        lesson("rising-wedge", "Rising Wedge", "Both lines up, converging. Can be bearish reversal or continuation — context first."),
        lesson("falling-wedge", "Falling Wedge", "Both lines down, converging."),
        lesson("broadening-pattern", "Broadening Pattern", "Expanding swings. Hard to trade; stops get hunted."),
        lesson("diamond-pattern", "Diamond Pattern", "Broadening then contracting. Rare and easy to force onto a chart."),
        lesson("harmonic-patterns", "Harmonic Patterns", "Fibonacci geometry (Gartley, Bat, Butterfly). Precise and easy to overfit. Always backtest."),
        lesson("gartley-pattern", "Gartley Pattern", "Specific retracement structure. Treat ratios as a hypothesis."),
        lesson("bat-pattern", "Bat Pattern", "Harmonic variant with a deeper B retracement."),
        lesson("butterfly-pattern", "Butterfly Pattern", "Harmonic extension pattern beyond the X-A origin."),
        lesson("abcd-pattern", "ABCD Pattern", "Simple measured-move geometry. Still not a signal by itself."),
      ]),
      mod("trend-indicators", "Trend indicators", [
        lesson("sma", "Simple Moving Average", "Average of closes. Lags. Good for regime, bad as a crystal ball."),
        lesson("ema", "Exponential Moving Average", "Weights recent closes more. Faster, noisier."),
        lesson("wma", "Weighted Moving Average", "Linear weights. A cousin of EMA."),
        lesson("macd", "MACD", "EMA difference plus signal line. Trend + momentum hybrid. Whipsaws in ranges."),
        lesson("adx", "ADX", "Measures trend strength, not direction. High ADX = trending; low = range."),
        lesson("supertrend", "Supertrend", "ATR-based trailing line. Excellent in trends, brutal in chop."),
        lesson("parabolic-sar", "Parabolic SAR", "Dots that flip with the trend. Same chop problem as Supertrend."),
        lesson("ichimoku", "Ichimoku Cloud", "A full system: cloud, twists, lagging span. Learn each piece before stacking rules."),
      ]),
      mod("momentum-vol-volume", "Momentum, volatility and volume", [
        lesson("rsi", "RSI", "0–100 momentum. 70/30 are conventions, not laws. Divergence is a hint, not a trigger."),
        lesson("stochastic", "Stochastic Oscillator", "Close vs recent range. Fast and noisy."),
        lesson("roc", "Rate of Change", "Percent change over N bars. Simple momentum."),
        lesson("cci", "Commodity Channel Index", "Deviation from a typical price mean. Unbounded."),
        lesson("williams-r", "Williams %R", "Stochastic inverted. Same information, different scale."),
        lesson("momentum-indicator", "Momentum Indicator", "Close minus close N bars ago. Same family as ROC."),
        lesson("atr", "Average True Range", "Typical bar range. Use it to size stops, not to predict direction."),
        lesson("bollinger-bands", "Bollinger Bands", "SMA ± standard deviations. Touches are not automatic reversals."),
        lesson("standard-deviation", "Standard Deviation", "Dispersion of returns. The building block of many vol tools."),
        lesson("historical-volatility", "Historical Volatility", "Realised vol over a lookback. Different from implied vol."),
        lesson("keltner-channels", "Keltner Channels", "EMA ± ATR bands. A calmer cousin of Bollinger."),
        lesson("volume-ma", "Volume Moving Average", "Is today unusual vs recent activity?"),
        lesson("volume-profile", "Volume Profile", "Volume by price, not by time. Highlights accepted prices."),
        lesson("vwap", "VWAP", "Volume-weighted average price for the session. Institutional benchmark, not a holy line."),
        lesson("anchored-vwap", "Anchored VWAP", "VWAP from a chosen event (earnings, swing). The anchor choice is subjective."),
        lesson("obv", "On-Balance Volume", "Cumulative volume signed by close direction. Divergences are noisy."),
        lesson("accumulation-distribution", "Accumulation/Distribution", "Close location inside the range, times volume."),
        lesson("mfi", "Money Flow Index", "RSI that includes volume. Still bounded 0–100."),
        lesson("chaikin-money-flow", "Chaikin Money Flow", "A/D over a lookback, normalised."),
      ]),
    ],
  },
  {
    id: 4,
    name: "Price Action and Market Structure",
    goal: "Describe swings, breaks of structure, and zones — then admit what is subjective and test it.",
    modules: [
      mod("structure", "Market structure", [
        lesson("swing-highs", "Swing highs", later),
        lesson("swing-lows", "Swing lows", later),
        lesson("higher-highs", "Higher highs", later),
        lesson("higher-lows", "Higher lows", later),
        lesson("lower-highs", "Lower highs", later),
        lesson("lower-lows", "Lower lows", later),
        lesson("uptrend", "Uptrend", later),
        lesson("downtrend", "Downtrend", later),
        lesson("sideways-market", "Sideways market", later),
        lesson("break-of-structure", "Break of Structure", later),
        lesson("change-of-character", "Change of Character", later),
        lesson("sr-zones", "Support and resistance zones", later),
        lesson("supply-zones", "Supply zones", later),
        lesson("demand-zones", "Demand zones", later),
        lesson("liquidity-zones", "Liquidity zones", later),
        lesson("stop-loss-hunting", "Stop-loss hunting", later),
        lesson("pa-false-breakouts", "False breakouts (price action)", later),
        lesson("price-imbalance", "Price imbalance", later),
        lesson("fair-value-gaps", "Fair value gaps", later),
        lesson("order-blocks", "Order blocks", later),
        lesson("trend-pullbacks", "Trend pullbacks", later),
        lesson("range-expansion", "Range expansion", later),
        lesson("range-contraction", "Range contraction", later),
        lesson("multi-timeframe-analysis", "Multi-timeframe analysis", later),
      ]),
    ],
  },
  {
    id: 5,
    name: "Fundamental Analysis",
    goal: "Read statements and ratios so you can spot weak businesses — valuation is a range, not a target price tip.",
    modules: [
      mod("statements", "Financial statements", [
        lesson("income-statement", "Income statement", later),
        lesson("balance-sheet", "Balance sheet", later),
        lesson("cash-flow-statement", "Cash-flow statement", later),
        lesson("annual-report", "Annual report", later),
        lesson("quarterly-results", "Quarterly results", later),
        lesson("earnings-calls", "Earnings calls", later),
      ]),
      mod("metrics", "Financial metrics", [
        lesson("revenue", "Revenue", later),
        lesson("revenue-growth", "Revenue growth", later),
        lesson("net-profit", "Net profit", later),
        lesson("profit-growth", "Profit growth", later),
        lesson("gross-margin", "Gross margin", later),
        lesson("operating-margin", "Operating margin", later),
        lesson("net-profit-margin", "Net profit margin", later),
        lesson("eps", "Earnings per share", later),
        lesson("pe-ratio", "Price-to-Earnings ratio", later),
        lesson("pb-ratio", "Price-to-Book ratio", later),
        lesson("peg-ratio", "PEG ratio", later),
        lesson("roe", "Return on Equity", later),
        lesson("roce", "Return on Capital Employed", later),
        lesson("debt-to-equity", "Debt-to-Equity ratio", later),
        lesson("interest-coverage", "Interest coverage ratio", later),
        lesson("current-ratio", "Current ratio", later),
        lesson("free-cash-flow", "Free cash flow", later),
        lesson("dividend-yield", "Dividend yield", later),
      ]),
      mod("company", "Company and economy", [
        lesson("business-model", "Business model", later),
        lesson("competitive-advantage", "Competitive advantage", later),
        lesson("management-quality", "Management quality", later),
        lesson("promoter-holding", "Promoter holding", later),
        lesson("promoter-pledging", "Promoter pledging", later),
        lesson("institutional-shareholding", "Institutional shareholding", later),
        lesson("competitor-comparison", "Competitor comparison", later),
        lesson("industry-analysis", "Industry analysis", later),
        lesson("sector-analysis", "Sector analysis", later),
        lesson("economic-cycles", "Economic cycles", later),
        lesson("interest-rates", "Interest rates", later),
        lesson("inflation", "Inflation", later),
        lesson("currency-movement", "Currency movement", later),
        lesson("company-valuation", "Company valuation", later),
        lesson("weak-companies", "Identifying financially weak companies", later),
      ]),
    ],
  },
  {
    id: 6,
    name: "Risk and Money Management",
    goal: "Size every trade from rupee risk. Pass this level before derivatives or algo modules unlock.",
    toolHref: { label: "Open position-size calculator", href: "/risk" },
    modules: [
      mod("risk-core", "Core risk", [
        lesson("risk-per-trade", "Risk per trade", "Decide in rupees before you decide in shares. Typical teaching range is 0.25–1% of capital per idea — pick a rule and keep it."),
        lesson("risk-to-reward", "Risk-to-reward ratio", "Target distance vs stop distance. 2:1 does not mean you will win. It means losers must be smaller than winners for the math to work at a given win rate."),
        lesson("position-sizing", "Position sizing", "Shares = rupee risk ÷ risk per share. This is the non-negotiable formula of the course."),
        lesson("portfolio-risk", "Portfolio risk", "Correlated names add up. Five ‘1%’ bank longs can be one 5% bet on rates."),
        lesson("diversification", "Diversification", "Uncorrelated return sources. 10 IT stocks is not diversification."),
        lesson("correlation", "Correlation", "How moves travel together. It spikes in crashes — the moment you needed it most."),
        lesson("max-daily-loss", "Maximum daily loss", "A hard stop for the day. Hit it, you are done. Protects you from revenge trading."),
        lesson("max-weekly-loss", "Maximum weekly loss", "A slower circuit breaker for a bad week."),
        lesson("max-portfolio-drawdown", "Maximum portfolio drawdown", "The hole you refuse to dig past. Strategy goes to paper or off."),
        lesson("gap-risk", "Gap risk", "Price can jump over your stop overnight or at the open. Cash-market gaps and derivative bases both do this."),
        lesson("liquidity-risk", "Liquidity risk", "You cannot exit at the backtest price if the book is empty."),
        lesson("market-risk", "Market risk", "The index can take your longs with it. Hedging is a cost, not a magic shield."),
        lesson("leverage-risk", "Leverage risk", "Borrowed exposure magnifies errors. This is why F&O stays locked."),
        lesson("risk-of-ruin", "Risk of ruin", "The chance a streak of losses ends the account. High risk-per-trade makes ruin a matter of time."),
        lesson("stop-loss-placement", "Stop-loss placement", "Place stops where the idea is wrong, then size to that distance. Do not pick size first and squeeze the stop."),
        lesson("trailing-stop", "Trailing stop loss", "Locks gains only if the market trends. In ranges it donates money to noise."),
        lesson("portfolio-rebalancing", "Portfolio rebalancing", "Restore target weights. Selling winners feels bad and is often the point."),
        lesson("capital-protection", "Capital protection", "The first job is staying in the game. Return is second."),
      ]),
    ],
  },
  {
    id: 7,
    name: "Strategy Formula Builder",
    goal: "Write entry, exit, stop, target and size as explicit rules. The AI will translate and warn — it will not bless a ‘profitable’ formula.",
    lockedUntil: "Complete Levels 1–6, including the risk assessment.",
    toolHref: { label: "Formula Builder (preview)", href: "/formulas" },
    modules: [
      mod("builder", "Builder", [
        lesson("formula-fields", "Available data fields", later),
        lesson("formula-operators", "Available operators", later),
        lesson("strategy-contract", "What every strategy must define", later),
        lesson("plain-language-conversion", "Plain-language conversion", later),
        lesson("formula-warnings", "Formula warnings", later),
      ]),
    ],
  },
  {
    id: 8,
    name: "Backtesting Laboratory",
    goal: "Simulate rules on history with costs. Learn bias names. Never treat a backtest as a forecast.",
    lockedUntil: "A saved strategy with stop-loss and position sizing.",
    modules: [
      mod("bt-features", "Lab features", [
        lesson("historical-data", "Historical market data", later),
        lesson("bt-timeframes", "Multiple timeframes", later),
        lesson("entry-exit-simulation", "Entry and exit simulation", later),
        lesson("brokerage-in-backtests", "Brokerage calculation", later),
        lesson("tax-in-backtests", "Tax calculation", later),
        lesson("slippage-in-backtests", "Slippage calculation", later),
        lesson("corporate-action-adjustment", "Corporate-action adjustment", later),
        lesson("benchmark-comparison", "Benchmark comparison", later),
        lesson("regime-testing", "Bull, bear and sideways testing", later),
        lesson("in-out-sample", "In-sample and out-of-sample testing", later),
        lesson("walk-forward", "Walk-forward testing", later),
        lesson("parameter-sensitivity", "Parameter-sensitivity testing", later),
        lesson("trade-report", "Trade-by-trade report", later),
      ]),
      mod("bt-metrics", "Performance metrics", [
        lesson("total-return", "Total return", later),
        lesson("net-return", "Net return after costs", later),
        lesson("cagr", "Annualized return", later),
        lesson("max-drawdown", "Maximum drawdown", later),
        lesson("win-rate", "Win rate", later),
        lesson("profit-factor", "Profit factor", later),
        lesson("expectancy", "Expectancy", later),
        lesson("sharpe-ratio", "Sharpe Ratio", later),
        lesson("sortino-ratio", "Sortino Ratio", later),
      ]),
      mod("bt-warnings", "Backtesting warnings", [
        lesson("look-ahead-bias", "Look-ahead bias", later),
        lesson("survivorship-bias", "Survivorship bias", later),
        lesson("overfitting", "Overfitting", later),
        lesson("insufficient-trades", "Insufficient trades", later),
      ]),
    ],
  },
  {
    id: 9,
    name: "Paper-Trading Simulator",
    goal: "Trade virtual capital with the same costs and journal rules you will need later. No live broker yet.",
    lockedUntil: "Risk assessment passed.",
    toolHref: { label: "Open simulator", href: "/simulator" },
    modules: [
      mod("paper", "Simulator", [
        lesson("virtual-balance", "Virtual trading balance", later),
        lesson("historical-simulation", "Historical market simulation", later),
        lesson("live-data-simulation", "Live-data simulation", later),
        lesson("sim-orders", "Buy, sell, stop and target orders", later),
        lesson("portfolio-tracking", "Portfolio tracking", later),
        lesson("sim-costs", "Brokerage and taxes", later),
        lesson("strategy-tagging", "Strategy tagging", later),
        lesson("journal-integration", "Trading journal integration", later),
        lesson("risk-limit-enforcement", "Risk-limit enforcement", later),
      ]),
    ],
  },
  {
    id: 10,
    name: "Futures and Options",
    goal: "Learn payoff, Greeks and defined-risk structures. Locked until risk training is passed. Max loss is shown before any options simulation.",
    lockedUntil: "Pass the risk-management assessment.",
    modules: [
      mod("futures", "Futures", [
        lesson("futures-contracts", "Futures contracts", later),
        lesson("lot-size", "Lot size", later),
        lesson("futures-expiry", "Expiry", later),
        lesson("margin", "Margin", later),
        lesson("mark-to-market", "Mark-to-market", later),
        lesson("leverage", "Leverage", later),
        lesson("rollover", "Rollover", later),
        lesson("hedging", "Hedging", later),
        lesson("futures-premium-discount", "Futures premium and discount", later),
      ]),
      mod("options", "Options", [
        lesson("call-option", "Call option", later),
        lesson("put-option", "Put option", later),
        lesson("strike-price", "Strike price", later),
        lesson("option-premium", "Option premium", later),
        lesson("intrinsic-time-value", "Intrinsic and time value", later),
        lesson("moneyness", "ITM, ATM, OTM", later),
        lesson("option-greeks", "Option Greeks", later),
        lesson("implied-volatility", "Implied volatility", later),
        lesson("option-chain", "Option chain", later),
        lesson("put-call-ratio", "Put-Call Ratio", later),
        lesson("payoff-diagram", "Payoff diagram", later),
      ]),
      mod("option-strategies", "Defined strategies", [
        lesson("covered-call", "Covered Call", later),
        lesson("protective-put", "Protective Put", later),
        lesson("bull-call-spread", "Bull Call Spread", later),
        lesson("bear-put-spread", "Bear Put Spread", later),
        lesson("iron-condor", "Iron Condor", later),
        lesson("long-straddle", "Long Straddle", later),
      ]),
    ],
  },
  {
    id: 11,
    name: "Algorithmic Trading",
    goal: "From rule-based thinking to event-driven systems, with kill switches, secrets handling and audit logs.",
    lockedUntil: "Paper-trading journal + risk assessment.",
    modules: [
      mod("algo-beginner", "Beginner", [
        lesson("what-is-an-algorithm", "What is an algorithm?", later),
        lesson("what-is-algo-trading", "What is algorithmic trading?", later),
        lesson("rule-based-trading", "Rule-based trading", later),
        lesson("discretionary-vs-algo", "Discretionary versus algorithmic", later),
        lesson("paper-trading-algo", "Paper trading for algos", later),
        lesson("apis-and-webhooks", "APIs and webhooks", later),
      ]),
      mod("algo-intermediate", "Intermediate", [
        lesson("trading-pseudocode", "Trading pseudocode", later),
        lesson("python-fundamentals", "Python fundamentals", later),
        lesson("ohlcv-in-code", "OHLCV data", later),
        lesson("indicator-calculations", "Indicator calculations", later),
        lesson("strategy-backtesting-code", "Strategy backtesting in code", later),
        lesson("logging-and-errors", "Logging and error handling", later),
      ]),
      mod("algo-advanced", "Advanced", [
        lesson("event-driven-architecture", "Event-driven architecture", later),
        lesson("order-management-systems", "Order-management systems", later),
        lesson("partial-fills-latency", "Partial fills, rate limits, latency", later),
        lesson("kill-switches", "Kill switches", later),
        lesson("secret-management", "Secret management", later),
        lesson("regulatory-requirements", "Regulatory requirements", later),
      ]),
    ],
  },
  {
    id: 12,
    name: "Capstone and Certification",
    goal: "Ship one researched, costed, out-of-sample tested strategy with paper-trade validation. Certificate only after this and the risk exam.",
    lockedUntil: "Levels 1–9 complete.",
    modules: [
      mod("capstone", "Capstone", [
        lesson("select-universe", "Select market and instruments", later),
        lesson("strategy-idea", "Define the strategy idea", later),
        lesson("market-logic", "Explain the market logic", later),
        lesson("entry-exit-formulas", "Create entry and exit formulas", later),
        lesson("capstone-risk-rules", "Stop-loss and position-sizing rules", later),
        lesson("capstone-backtest", "Backtest with costs", later),
        lesson("regime-and-oos", "Regime and out-of-sample tests", later),
        lesson("limitations-report", "Explain limitations", later),
        lesson("paper-validation", "Paper-trading validation", later),
      ]),
    ],
  },
];

export const ALL_LESSONS: CurriculumLesson[] = LEVELS.flatMap((level) =>
  level.modules.flatMap((m) => m.lessons),
);

export function getLevel(id: number): CurriculumLevel | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function findLesson(
  slug: string,
): { lesson: CurriculumLesson; module: CurriculumModule; level: CurriculumLevel } | undefined {
  for (const level of LEVELS) {
    for (const module of level.modules) {
      const lesson = module.lessons.find((item) => item.slug === slug);
      if (lesson) return { lesson, module, level };
    }
  }
  return undefined;
}

export function nextPublishedLesson(slug: string): CurriculumLesson | undefined {
  const published = ALL_LESSONS.filter((l) => l.status === "published");
  const index = published.findIndex((l) => l.slug === slug);
  if (index < 0) return undefined;
  return published[index + 1];
}

export function courseStats() {
  return {
    levels: LEVELS.length,
    lessons: ALL_LESSONS.length,
    published: ALL_LESSONS.filter((l) => l.status === "published").length,
  };
}
