import type { LessonBody, PatternWorkbook } from "./types";

const NOT_A_SIGNAL =
  "A candlestick pattern is not a guaranteed trading signal. It is one bar of psychology. Wait for the next close, check volume and structure, and always define invalidation in rupees before size.";

function pattern(partial: PatternWorkbook): LessonBody {
  return {
    paragraphs: [NOT_A_SIGNAL],
    takeaways: [
      "Name the timeframe you are reading.",
      "The pattern describes the last 1–3 bars, not the next month.",
      "If you cannot write a stop, you do not have a trade.",
    ],
    pattern: partial,
  };
}

export const LESSON_CONTENT: Record<string, LessonBody> = {
  "what-is-the-stock-market": {
    paragraphs: [
      "A stock market is a regulated venue where buyers and sellers exchange claims on companies. In India that venue is primarily the NSE and BSE, with clearing corporations and depositories sitting underneath so trades can settle.",
      "You are not competing with a slot machine. You are participating in an auction. Someone is always on the other side of your order. They may know more, care less, or simply need liquidity. Education here is about process, not prediction.",
    ],
    takeaways: [
      "Markets transfer ownership; they do not owe you a return.",
      "Stocktute is a simulator and classroom — never a tip desk.",
    ],
  },
  "how-the-stock-market-works": {
    paragraphs: [
      "Orders rest in an electronic book. Matching engines pair compatible bids and asks. The last match is the ‘price’ you see on a chart — a print, not a verdict.",
      "When buy interest overwhelms sell interest at a level, the next prints are higher. The reverse is a decline. News, flows, and positioning all show up as this imbalance. Charts are the footprint, not the cause.",
    ],
  },
  "nse-and-bse": {
    paragraphs: [
      "The National Stock Exchange (NSE) hosts most of India’s cash-equity and derivatives activity. The Bombay Stock Exchange (BSE) is older and still lists a wide universe. Index products, F&O liquidity, and ‘the market’ that day-traders mean are usually NSE.",
      "Listing on an exchange is not a quality stamp. Illiquid BSE-only names can have wide spreads and circuit limits that trap you. Always check where the liquidity actually is.",
    ],
  },
  "nifty-50-and-sensex": {
    paragraphs: [
      "Nifty 50 and Sensex are benchmarks. They answer ‘how did large Indian equities do?’ They are not a stock. To get similar exposure you use an index fund or ETF, which has tracking error and fees.",
      "A stock can crush its index or die while the index makes highs. Never confuse a ticker’s story with the average.",
    ],
  },
  "timeframes": {
    paragraphs: [
      "A 5-minute downtrend inside a weekly uptrend is normal. Traders who mix those sentences without naming the timeframe talk past each other — and blow stops.",
      "Pick one decision timeframe, one higher timeframe for bias, and one lower timeframe for execution. If they conflict, stand aside. Standing aside is a position.",
    ],
    takeaways: [
      "Always say the timeframe out loud before you describe a trend.",
      "Classroom default for study is 15-minute; daily is better for classic patterns.",
    ],
  },
  "candlestick-chart": {
    paragraphs: [
      "Each candle compresses every trade in a bucket of time into open, high, low, close. The body is the net result; the wicks are the rejected extremes.",
      "Green (close > open) does not mean ‘buy’. It means that bar’s auction ended higher than it started. The next bar can erase it. Use the classroom to see this live.",
    ],
  },
  "position-sizing": {
    paragraphs: [
      "Size is not a vibe. Maximum rupee risk = account capital × risk percent. Risk per share = entry − stop. Position size = rupee risk ÷ risk per share. If the stop is ₹10 away and you may only lose ₹1,000, you buy 100 shares — not whatever ‘looks cheap’.",
      "If the calculated size is too small to feel exciting, that is the point. Excitement is how accounts die. Use the calculator on the Risk page and journal the numbers.",
    ],
    takeaways: [
      "Stop first, size second — never the reverse.",
      "Correlated positions share risk even if each ticket looks like 1%.",
    ],
  },
  "risk-per-trade": {
    paragraphs: [
      "Risk per trade is the amount you accept as lost if the idea is wrong — not the amount you hope to make. Teaching default: 1% or less of equity.",
      "A 10-loss streak at 1% is painful and recoverable. A 10-loss streak at 10% is a career event. The platform will not unlock F&O until you can apply this without prompting.",
    ],
  },

  doji: pattern({
    definition: "A candle whose open and close are almost the same, so the real body is a thin line.",
    psychology: "Buyers and sellers fought and neither kept the close. The market paused.",
    rules: [
      "Body is a small fraction of the full range (high–low).",
      "Read it only in context of the prior trend.",
      "The next candle decides whether the pause was rest or reversal.",
    ],
    meaning: "Neutral until confirmed. Not a buy. Not a sell.",
    trend: "After a long run, a doji is a warning that energy faded — still not a reverse-the-book order.",
    volume: "A doji on a volume spike is a more serious pause than a doji on a dead bar.",
    entry: "None on the doji itself. If you trade it, wait for a close that breaks the doji high/low in your direction.",
    stop: "Beyond the opposite wick of the doji (or the pattern that contains it).",
    target: "At least 1:1 to the stop, preferably 2:1, taken from structure — not from hope.",
    invalidation: "A close back through the doji range against your idea cancels it.",
    success: "Downtrend, doji, then a wide-range green bar that holds. You entered after that close.",
    failed: "You bought the doji in a crash and the next three bars were red. The doji was a pause in selling, not a bottom.",
    exercise: "In AI Classroom, find a doji on 15m and write whether the next bar confirmed or denied it.",
  }),
  "long-legged-doji": pattern({
    definition: "A doji with long upper and lower wicks — a wide auction that closed near unchanged.",
    psychology: "Both sides had a turn. The close is a truce, not a victory.",
    rules: ["Large range relative to body.", "Open and close sit near the midpoint.", "Ignore it inside a tight range of other spinning tops."],
    meaning: "High indecision. Expect a larger next bar.",
    trend: "More meaningful after a directional run than in a chop.",
    volume: "High volume long-legged doji = more participants failed to hold a direction.",
    entry: "Break and close beyond the doji high or low, not a wick poke.",
    stop: "The far wick of the doji.",
    target: "Prior swing; never ‘because the doji was big’.",
    invalidation: "Immediate close back inside the doji after your breakout entry.",
    success: "Trend, long-legged doji, expansion bar in the new direction that holds.",
    failed: "You faded the wick and got run over by a trend day.",
    exercise: "Mark one long-legged doji and note the next bar’s range versus the doji range.",
  }),
  "dragonfly-doji": pattern({
    definition: "Open, high and close clustered at the top; a long lower wick.",
    psychology: "Sellers pushed it down; buyers took it back by the close.",
    rules: ["Lower wick much longer than the body.", "Upper wick tiny.", "Best studied after a decline."],
    meaning: "Potentially bullish rejection — confirmation required.",
    trend: "After a selloff. In a rally it is just a weird bar.",
    volume: "Prefer above-average volume on the rejection.",
    entry: "Next bar close above the dragonfly high.",
    stop: "Below the dragonfly low.",
    target: "Prior swing high or 2× risk.",
    invalidation: "Close below the dragonfly low.",
    success: "Selloff, dragonfly, follow-through green bar.",
    failed: "Dragonfly, then a gap down through the low. The rejection failed.",
    exercise: "Find a dragonfly and measure stop distance in rupees before imagining the target.",
  }),
  "gravestone-doji": pattern({
    definition: "Open, low and close clustered at the bottom; a long upper wick.",
    psychology: "Buyers pushed it up; sellers took it back by the close.",
    rules: ["Upper wick dominates.", "Lower wick tiny.", "Best after a rally."],
    meaning: "Potentially bearish rejection — confirmation required.",
    trend: "After an advance.",
    volume: "Prefer a volume spike on the failed push up.",
    entry: "Next close below the gravestone low.",
    stop: "Above the gravestone high.",
    target: "Prior swing low or 2× risk.",
    invalidation: "Close above the high.",
    success: "Rally, gravestone, follow-through red bar.",
    failed: "Gravestone in a squeeze that immediately makes new highs.",
    exercise: "On the classroom chart, wait for the next close — do not short the wick.",
  }),
  hammer: pattern({
    definition: "Small real body near the high of the bar with a lower wick at least twice the body, appearing after a decline.",
    psychology: "Auction went down, buyers rejected the low, close recovered.",
    rules: [
      "Lower wick ≥ 2× body.",
      "Upper wick small.",
      "Prior bar(s) should show selling so there is something to reverse.",
    ],
    meaning: "Bullish reversal *attempt*. Not a market order to buy.",
    trend: "Requires a downswing first. A ‘hammer’ in a flat range is just a bar.",
    volume: "Better if the rejection prints on rising volume.",
    entry: "Close above the hammer high, or a conservative buy stop above that high.",
    stop: "Below the hammer low. If that stop is huge, skip — do not shrink the stop.",
    target: "First prior swing high, or 2× the hammer range.",
    invalidation: "Close below the hammer low, or a failure to follow through within 1–3 bars.",
    success: "Down-move, hammer, next bar holds above the body and pushes.",
    failed: "Hammer, then a breakdown through the low the next session. The rejection was temporary.",
    exercise: "Open Classroom, switch to 15m, click Hammer in the pattern list, and write the stop in ₹.",
  }),
  "hanging-man": pattern({
    definition: "Same shape as a hammer, but it prints after a rally.",
    psychology: "Sellers were able to drive price down intra-bar even though buyers closed it near the high. That is a warning, not a short.",
    rules: ["Hammer geometry.", "Must appear after an advance.", "Bearish only with a weak next close."],
    meaning: "Potentially bearish; unconfirmed it is noise.",
    trend: "Uptrend or sharp bounce.",
    volume: "A high-volume hanging man is more of a caution than a quiet one.",
    entry: "Only after a close below the hanging-man low.",
    stop: "Above its high.",
    target: "Prior swing or 2× risk.",
    invalidation: "Immediate new high.",
    success: "Extended rally, hanging man, next day gaps/closes down.",
    failed: "You shorted the hanging man and the trend day continued up.",
    exercise: "Compare a hammer and hanging man that look identical. The only difference that matters is location.",
  }),
  "inverted-hammer": pattern({
    definition: "Small body near the low, long upper wick, after a decline.",
    psychology: "Buyers probed higher but could not hold. Still, they showed up after a drop.",
    rules: ["Upper wick ≥ 2× body.", "Lower wick small.", "After selling."],
    meaning: "Bullish only if the next close is strong.",
    trend: "Downswing required.",
    volume: "Confirmation bar should not be dead.",
    entry: "Next close above the inverted-hammer high.",
    stop: "Below its low.",
    target: "2× risk or prior supply.",
    invalidation: "Failure to take out the high, then a new low.",
    success: "Inverted hammer, then a marubozu-like green bar.",
    failed: "Inverted hammer, then another lower low. Probe failed.",
    exercise: "Do not enter inside the wick. Write that rule on your journal card.",
  }),
  "shooting-star": pattern({
    definition: "Small body near the low, long upper wick, after a rally.",
    psychology: "Buyers made a new high and were rejected by the close.",
    rules: ["Upper wick ≥ 2× body.", "After an advance.", "Body in the lower third of the range."],
    meaning: "Bearish reversal *attempt*.",
    trend: "Needs an upswing.",
    volume: "Rejection volume helps; quiet stars fail more.",
    entry: "Close below the star low.",
    stop: "Above the star high.",
    target: "Prior swing low / 2× risk.",
    invalidation: "Close above the high.",
    success: "Rally into resistance, shooting star, next bar red and holds.",
    failed: "Star in a squeeze; next bar gaps up. You shorted a strong trend.",
    exercise: "Find a shooting star on Classroom and check whether it sat at a prior high.",
  }),
  "bullish-marubozu": pattern({
    definition: "Open near the low, close near the high, almost no wicks.",
    psychology: "Buyers controlled the whole bar.",
    rules: ["Wicks tiny versus body.", "Close > open.", "One bar of control, not a system."],
    meaning: "Bullish pressure in that bar.",
    trend: "In a downtrend it can be a reversal bar; in an uptrend, continuation. Label the trend first.",
    volume: "Should expand. A quiet marubozu is less convincing.",
    entry: "Not blindly. Break of high with a stop under the bar, only if size still fits 1% risk.",
    stop: "Below the marubozu low.",
    target: "Measured from the bar range or structure.",
    invalidation: "Close back inside or below the bar.",
    success: "Breakout bar that holds as support next session.",
    failed: "Marubozu at the high of a 10-day run, then a gap down. Late.",
    exercise: "Compute position size using the full bar as stop. If size is tiny, skip.",
  }),
  "bearish-marubozu": pattern({
    definition: "Open near the high, close near the low, almost no wicks.",
    psychology: "Sellers controlled the whole bar.",
    rules: ["Wicks tiny.", "Close < open."],
    meaning: "Bearish pressure in that bar.",
    trend: "Context first.",
    volume: "Prefer expansion.",
    entry: "Only with a plan and a stop above the high.",
    stop: "Above the marubozu high.",
    target: "Structure / 2× risk.",
    invalidation: "Close back above the bar.",
    success: "Breakdown that is not bought next bar.",
    failed: "Bearish marubozu into support that immediately reverses. Capitulation bar.",
    exercise: "Journal whether you would have had room to place the stop without violating 1% risk.",
  }),
  "spinning-top": pattern({
    definition: "Small body with wicks on both sides — a milder doji.",
    psychology: "Balance. Neither side committed.",
    rules: ["Small body.", "Visible wicks both ways.", "A sequence of spinning tops = chop."],
    meaning: "Neutral.",
    trend: "Inside a trend it is a rest. At extremes it can precede a turn.",
    volume: "Low-volume spinning tops are just quiet tape.",
    entry: "None.",
    stop: "N/A until a directional bar appears.",
    target: "N/A.",
    invalidation: "N/A.",
    success: "You stood aside in a spinning-top cluster and waited.",
    failed: "You forced a direction onto indecision bars.",
    exercise: "Count how many spinning tops appear in a lunch-hour range on 5m.",
  }),
  "bullish-engulfing": pattern({
    definition: "A green candle whose body fully covers the previous red body, typically after a decline.",
    psychology: "Sellers had the last bar; this bar buyers took the whole thing back and then some.",
    rules: [
      "Prior bar bearish.",
      "Current open at or below prior close, current close at or above prior open.",
      "Current body larger than prior body.",
    ],
    meaning: "Bullish reversal *attempt* at the bar-to-bar level.",
    trend: "Needs a downswing. Engulfing in the middle of nowhere is just overlap.",
    volume: "Second bar should not be quiet.",
    entry: "Next open or a stop above the engulfing high, if risk fits.",
    stop: "Below the two-bar low.",
    target: "2× the two-bar risk or last swing high.",
    invalidation: "Close below the pattern low.",
    success: "Selloff, engulfing at a level, follow-through.",
    failed: "Engulfing in a waterfall; next bar makes a new low. You bought a falling knife with a pretty name.",
    exercise: "Use Classroom’s pattern list, click Bullish Engulfing, and write the two-bar low as your invalidation.",
  }),
  "bearish-engulfing": pattern({
    definition: "A red candle whose body fully covers the previous green body after a rally.",
    psychology: "Buyers’ last bar is completely reversed.",
    rules: ["Prior bullish.", "Current body engulfs prior body.", "After an advance."],
    meaning: "Bearish reversal attempt.",
    trend: "Needs an upswing.",
    volume: "Expansion on the red bar helps.",
    entry: "Close below the pattern, or stop under the low.",
    stop: "Above the two-bar high.",
    target: "2× risk / last swing low.",
    invalidation: "Close above the pattern high.",
    success: "Rally into resistance, engulfing, follow-through.",
    failed: "Bearish engulfing in a squeeze that immediately recovers.",
    exercise: "Measure the stop. If it violates 1% at even 1 share lot, pass.",
  }),
  "bullish-harami": pattern({
    definition: "A small body contained inside the prior large bearish body.",
    psychology: "Selling pressure stalled. The market printed a inside bar.",
    rules: ["Day 1 large red.", "Day 2 body inside day 1 body.", "Not yet a reversal."],
    meaning: "Pause that *may* turn. Three-inside-up is the confirmation version.",
    trend: "After a decline.",
    volume: "Day 2 often contracts. Expansion comes on the confirm bar.",
    entry: "Only after a close above day 1 high (or the harami high).",
    stop: "Below the two-bar low.",
    target: "Structure.",
    invalidation: "Close below the low.",
    success: "Harami, then a third bar that breaks up.",
    failed: "Harami, then continuation down. It was a rest in the trend.",
    exercise: "Do not enter the inside bar. Write the confirm rule in your journal.",
  }),
  "bearish-harami": pattern({
    definition: "A small body inside a prior large bullish body.",
    psychology: "Buying stalled.",
    rules: ["Large green then small inside body.", "Wait for three-inside-down if you need confirmation."],
    meaning: "Pause, possibly bearish.",
    trend: "After a rally.",
    volume: "Contraction then expansion on the break.",
    entry: "Close below the pattern low.",
    stop: "Above the two-bar high.",
    target: "Structure / 2× risk.",
    invalidation: "New high.",
    success: "Harami at a high, third bar breaks down.",
    failed: "Inside bar in a strong trend that simply continues up.",
    exercise: "Label one harami as ‘rest’ vs ‘turn’ only after the third bar.",
  }),
  "piercing-line": pattern({
    definition: "After a red candle, a green candle opens weaker and closes above the midpoint of the prior body.",
    psychology: "Gap/open in the sellers’ favour, then buyers reclaim more than half the prior body.",
    rules: ["Prior bearish.", "Open below prior close/low area.", "Close > midpoint of prior body, but not a full engulf."],
    meaning: "Bullish reversal attempt, weaker than a full engulfing.",
    trend: "Downswing.",
    volume: "Second bar volume should show up.",
    entry: "Next close holding the midpoint.",
    stop: "Below the two-bar low.",
    target: "2× risk.",
    invalidation: "Close back below the midpoint then the low.",
    success: "Piercing at support with follow-through.",
    failed: "Piercing in a crash, next bar red.",
    exercise: "Draw the prior body’s midpoint before you name the pattern.",
  }),
  "dark-cloud-cover": pattern({
    definition: "After a green candle, a red candle opens stronger and closes below the midpoint of the prior body.",
    psychology: "Buyers get a hopeful open, then lose the midpoint.",
    rules: ["Prior bullish.", "Open above prior close/high area.", "Close < midpoint of prior body."],
    meaning: "Bearish reversal attempt.",
    trend: "Upswing.",
    volume: "Second bar should participate.",
    entry: "Next close remaining weak.",
    stop: "Above the two-bar high.",
    target: "2× risk.",
    invalidation: "Reclaim of the midpoint and high.",
    success: "Dark cloud at resistance.",
    failed: "Cloud in a squeeze, next bar new high.",
    exercise: "Same midpoint discipline as piercing line, inverted.",
  }),
  "tweezer-top": pattern({
    definition: "Two (or more) bars sharing nearly the same high after a rally.",
    psychology: "A ceiling where supply keeps showing up.",
    rules: ["Similar highs.", "After an advance.", "The second bar should fail to hold strength."],
    meaning: "Resistance hypothesis.",
    trend: "Uptrend or bounce.",
    volume: "Second rejection on volume is better.",
    entry: "Close below the two-bar low.",
    stop: "Above the shared high.",
    target: "2× risk.",
    invalidation: "Clean close above the tweezer high.",
    success: "Double tap of a known high, then a breakdown.",
    failed: "Tweezers that become a bull flag.",
    exercise: "Check if the highs are actually equal or you are forcing it.",
  }),
  "tweezer-bottom": pattern({
    definition: "Two bars sharing nearly the same low after a decline.",
    psychology: "A floor where demand keeps showing up.",
    rules: ["Similar lows.", "After a decline."],
    meaning: "Support hypothesis.",
    trend: "Downswing.",
    volume: "Second hold on volume helps.",
    entry: "Close above the two-bar high.",
    stop: "Below the shared low.",
    target: "2× risk.",
    invalidation: "Close below the tweezer low.",
    success: "Double tap of a known low, then a bounce that holds.",
    failed: "Tweezers that break on the third test.",
    exercise: "Count tests. Third test of a ‘tweezer’ is often the break.",
  }),
  "morning-star": pattern({
    definition: "Three bars: a long red, a small-bodied gap/indecision bar, then a strong green that closes well into the first bar’s body.",
    psychology: "Selling, pause, buyers take control.",
    rules: [
      "Bar 1 bearish and substantial.",
      "Bar 2 small (star or doji).",
      "Bar 3 bullish and closes above the midpoint of bar 1.",
    ],
    meaning: "Bullish three-bar reversal attempt.",
    trend: "Must follow a decline.",
    volume: "Bar 3 should show real volume.",
    entry: "Close of bar 3, or next open if it holds.",
    stop: "Below the three-bar low (usually bar 2’s low).",
    target: "2× the three-bar risk or last swing.",
    invalidation: "Close below the star low.",
    success: "Selloff, star, wide green bar that holds as support.",
    failed: "A ‘star’ that is just three overlapping bars in a range. You invented a pattern.",
    exercise: "In Classroom, jump to a Morning Star marker and verify all three rules, not just the name.",
  }),
  "evening-star": pattern({
    definition: "Long green, small star, strong red closing into the first body — after a rally.",
    psychology: "Buying, pause, sellers take control.",
    rules: ["Bar 1 bullish.", "Bar 2 small.", "Bar 3 bearish, closes below midpoint of bar 1."],
    meaning: "Bearish three-bar reversal attempt.",
    trend: "Needs an advance.",
    volume: "Bar 3 participation.",
    entry: "Close of bar 3 if your size still respects 1% with a stop above the star.",
    stop: "Above the three-bar high.",
    target: "2× risk.",
    invalidation: "Close above the star high.",
    success: "Climax rally, star, wide red bar.",
    failed: "Evening star mid-trend that is bought immediately.",
    exercise: "Write max loss in ₹ before looking at the ‘perfect’ picture.",
  }),
  "morning-doji-star": pattern({
    definition: "A morning star whose middle bar is a doji.",
    psychology: "Even more indecision in the middle before buyers take over.",
    rules: ["Morning-star structure.", "Middle bar is a doji."],
    meaning: "Bullish attempt with a clearer pause.",
    trend: "Downswing.",
    volume: "Bar 3 must confirm.",
    entry: "Bar 3 close.",
    stop: "Below the doji low.",
    target: "2× risk.",
    invalidation: "Close below the doji.",
    success: "Doji star that is not immediately sold.",
    failed: "Doji star, then a fourth bar new low.",
    exercise: "Compare morning star vs morning doji star on the same symbol.",
  }),
  "evening-doji-star": pattern({
    definition: "Evening star whose middle bar is a doji.",
    psychology: "Hope pauses as a doji, then selling returns.",
    rules: ["Evening-star structure.", "Middle doji."],
    meaning: "Bearish attempt.",
    trend: "Upswing.",
    volume: "Bar 3.",
    entry: "Bar 3 close.",
    stop: "Above the doji high.",
    target: "2× risk.",
    invalidation: "Close above the doji.",
    success: "Doji at the high, then a real red bar.",
    failed: "Doji that becomes a bull flag.",
    exercise: "No entry on the doji. Only on bar 3.",
  }),
  "three-white-soldiers": pattern({
    definition: "Three consecutive green candles with higher closes, often opening in the prior body.",
    psychology: "Persistent buying.",
    rules: ["Three bullish closes.", "Each close higher.", "Opens not violently gapping if you want ‘textbook’."],
    meaning: "Bullish continuation — and a late-trend risk.",
    trend: "Works as continuation. At the 8th up day it is often exhaustion.",
    volume: "Should not dry up bar after bar.",
    entry: "Usually too late to chase. Prefer pullbacks after the three.",
    stop: "Under the three-bar low if you must engage.",
    target: "Trail; do not assume a fourth soldier.",
    invalidation: "A wide red bar through the soldiers.",
    success: "Soldiers out of a base, then a flag.",
    failed: "Soldiers at the high of a parabolic move. You bought the climax.",
    exercise: "Count how many soldiers already printed before you feel FOMO.",
  }),
  "three-black-crows": pattern({
    definition: "Three consecutive red candles with lower closes.",
    psychology: "Persistent selling.",
    rules: ["Three bearish closes, each lower."],
    meaning: "Bearish continuation — or capitulation.",
    trend: "Continuation vs climax depends on how stretched the move is.",
    volume: "Climax volume vs orderly volume tell different stories.",
    entry: "Do not blindly short the third crow. Prefer a bounce that fails.",
    stop: "Above the three-bar high.",
    target: "Trail / structure.",
    invalidation: "Strong green reversal bar.",
    success: "Crows from a topping range.",
    failed: "Crows into a major daily support that instantly reverses.",
    exercise: "Mark whether the third crow is extended versus ATR.",
  }),
  "three-inside-up": pattern({
    definition: "Bullish harami plus a third bar that closes above the first bar’s high.",
    psychology: "Pause, then confirmation that buyers took the range.",
    rules: ["Harami first.", "Bar 3 confirms upward."],
    meaning: "More complete than a raw harami.",
    trend: "Downswing.",
    volume: "Bar 3 should speak.",
    entry: "Bar 3 close.",
    stop: "Below the pattern low.",
    target: "2× risk.",
    invalidation: "Close below the low.",
    success: "Textbook three-inside-up at support.",
    failed: "Bar 3 barely closes up and immediately reverses.",
    exercise: "Wait for bar 3. That is the whole lesson.",
  }),
  "three-inside-down": pattern({
    definition: "Bearish harami plus a third bar that closes below the first bar’s low.",
    psychology: "Pause, then sellers take the range.",
    rules: ["Bearish harami.", "Bar 3 confirms down."],
    meaning: "Confirmed pause-to-down.",
    trend: "Upswing.",
    volume: "Bar 3.",
    entry: "Bar 3 close.",
    stop: "Above the pattern high.",
    target: "2× risk.",
    invalidation: "Close above the high.",
    success: "At resistance with follow-through.",
    failed: "Bar 3 dip bought aggressively.",
    exercise: "Same patience rule as three-inside-up.",
  }),
  "three-outside-up": pattern({
    definition: "Bullish engulfing plus a third bar that closes higher.",
    psychology: "Reversal bar, then confirmation.",
    rules: ["Engulfing first.", "Bar 3 higher close."],
    meaning: "Stronger bullish three-bar set.",
    trend: "Downswing.",
    volume: "Should expand across 2–3.",
    entry: "Bar 3 close if stop still fits.",
    stop: "Below the engulfing low.",
    target: "2× risk.",
    invalidation: "Close below the low.",
    success: "Outside-up that holds.",
    failed: "Bar 3 is a tiny doji and then fails. Confirmation was fake.",
    exercise: "If bar 3 is weak, you do not have three-outside-up.",
  }),
  "three-outside-down": pattern({
    definition: "Bearish engulfing plus a third lower close.",
    psychology: "Reversal bar, then confirmation lower.",
    rules: ["Bearish engulfing.", "Bar 3 lower close."],
    meaning: "Stronger bearish three-bar set.",
    trend: "Upswing.",
    volume: "Expansion.",
    entry: "Bar 3 close.",
    stop: "Above the engulfing high.",
    target: "2× risk.",
    invalidation: "Close above the high.",
    success: "Outside-down from a high.",
    failed: "Bar 3 is bought. Trap.",
    exercise: "Journal the stop in ₹. Walk away if size is silly.",
  }),
};

export function getLessonContent(slug: string): LessonBody | undefined {
  return LESSON_CONTENT[slug];
}
